apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ysuowz6hv-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ysuowz6hv-python 
  name: ysuowz6hv-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ysuowz6hv-python 
